import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class LoginService {
  loginSubject$ = new BehaviorSubject<boolean>(false);

  /**
   * It saves a token when user loggedIn successfully.
   * @param token generated by backend.
   */
  loginUser(token: string) {
    localStorage.setItem('token', token);
  }

  /**
   * It logout the user.
   */
  logoutUser() {
    localStorage.removeItem('token');
    this.loginSubject$.next(false);
  }

  /**
   * It checks if user loggedIn or not.
   * @returns boolean.
   */
  isUserLoggedIn() {
    const token = localStorage.getItem('token');
    if (token == null || token == undefined || token == '') return false;
    return true;
  }
}
