import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class LoginService {
  loginSubject$ = new BehaviorSubject<boolean>(false);

  /**
   * It saves a token when user loggedIn successfully.
   * @param token generated by backend.
   */
  loginUser(token: string, user_id: string): void {
    localStorage.setItem('token', token);
    localStorage.setItem('user_id', user_id);
  }

  /**
   * It logout the user.
   */
  logoutUser(): void {
    localStorage.removeItem('token');
    localStorage.removeItem('user_id');
    this.loginSubject$.next(false);
  }

  /**
   * It checks if user loggedIn or not.
   * @returns boolean.
   */
  isUserLoggedIn(): boolean {
    const token = localStorage.getItem('token');
    return !!token;
  }
}
